sudo: false
language: node_js

node_js:
  - 10 # use nodejs v10 LTS

cache: npm

before_install:
  - git config --global user.name 'ff-xingyun'
  - git config --global user.email 'stefan.gufan@gmail.com'
  - npm install -g hexo-cli

install:
  - npm i

branches:
  only:
    - source # build master branch only

script:
  - hexo clean
  - hexo generate # generate static files

after_success:
  - cd ./public
  - git init
  - git add --all .
  - git commit -m "Travis CI Auto Builder"
  - git push --quiet --force https://$GH_TOKEN@github.com/ff-xingyun/ff-xingyun.github.io.git master